name: uran
description: تطبيق قرآن كريم - رفيقك اليومي مع كتاب الله
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  just_audio: ^0.9.36

flutter:
  uses-material-design: true